apiVersion: 1

policies:
  - orgId: 1
    receiver: Honeypot-Webhook
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Honeypot-Webhook
        matchers:
          - severity = critical
        group_wait: 0s
        repeat_interval: 30m
      - receiver: Honeypot-Webhook
        matchers:
          - severity = warning
        group_wait: 2m
        repeat_interval: 4h
