apiVersion: 1

datasources:
  - name: InfluxDB
    uid: efj3ikja6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: honeypot
      defaultBucket: attacks
      tlsSkipVerify: true
    secureJsonData:
      token: honeypot-super-secret-token
    editable: true
