/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_HONEYPOT_EVENT_PB_H_INCLUDED
#define PB_HONEYPOT_EVENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* HoneypotEvent — compact binary encoding for ESP32 → MQTT → backend
 nanopb options file (honeypot_event.options) constrains string sizes. */
typedef struct _HoneypotEventPb {
    uint32_t timestamp;
    char proto[8];
    char src_ip[16];
    char username[32];
    char password[32];
    char command[128];
    char event_type[24];
    char node[16];
    uint32_t pattern_id;
    char pattern_name[36];
    char pattern_group[4];
    uint32_t confidence;
    char session_id[8];
    uint32_t attempt_num;
    uint32_t session_duration_ms;
    char botnet_family[20];
    char mitre_technique[12];
} HoneypotEventPb;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HoneypotEventPb_init_default             {0, "", "", "", "", "", "", "", 0, "", "", 0, "", 0, 0, "", ""}
#define HoneypotEventPb_init_zero                {0, "", "", "", "", "", "", "", 0, "", "", 0, "", 0, 0, "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define HoneypotEventPb_timestamp_tag            1
#define HoneypotEventPb_proto_tag                2
#define HoneypotEventPb_src_ip_tag               3
#define HoneypotEventPb_username_tag             4
#define HoneypotEventPb_password_tag             5
#define HoneypotEventPb_command_tag              6
#define HoneypotEventPb_event_type_tag           7
#define HoneypotEventPb_node_tag                 8
#define HoneypotEventPb_pattern_id_tag           9
#define HoneypotEventPb_pattern_name_tag         10
#define HoneypotEventPb_pattern_group_tag        11
#define HoneypotEventPb_confidence_tag           12
#define HoneypotEventPb_session_id_tag           13
#define HoneypotEventPb_attempt_num_tag          14
#define HoneypotEventPb_session_duration_ms_tag  15
#define HoneypotEventPb_botnet_family_tag        16
#define HoneypotEventPb_mitre_technique_tag      17

/* Struct field encoding specification for nanopb */
#define HoneypotEventPb_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   SINGULAR, STRING,   proto,             2) \
X(a, STATIC,   SINGULAR, STRING,   src_ip,            3) \
X(a, STATIC,   SINGULAR, STRING,   username,          4) \
X(a, STATIC,   SINGULAR, STRING,   password,          5) \
X(a, STATIC,   SINGULAR, STRING,   command,           6) \
X(a, STATIC,   SINGULAR, STRING,   event_type,        7) \
X(a, STATIC,   SINGULAR, STRING,   node,              8) \
X(a, STATIC,   SINGULAR, UINT32,   pattern_id,        9) \
X(a, STATIC,   SINGULAR, STRING,   pattern_name,     10) \
X(a, STATIC,   SINGULAR, STRING,   pattern_group,    11) \
X(a, STATIC,   SINGULAR, UINT32,   confidence,       12) \
X(a, STATIC,   SINGULAR, STRING,   session_id,       13) \
X(a, STATIC,   SINGULAR, UINT32,   attempt_num,      14) \
X(a, STATIC,   SINGULAR, UINT32,   session_duration_ms,  15) \
X(a, STATIC,   SINGULAR, STRING,   botnet_family,    16) \
X(a, STATIC,   SINGULAR, STRING,   mitre_technique,  17)
#define HoneypotEventPb_CALLBACK NULL
#define HoneypotEventPb_DEFAULT NULL

extern const pb_msgdesc_t HoneypotEventPb_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HoneypotEventPb_fields &HoneypotEventPb_msg

/* Maximum encoded size of messages (where known) */
#define HONEYPOT_EVENT_PB_H_MAX_SIZE             HoneypotEventPb_size
#define HoneypotEventPb_size                     381

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
